/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedAgentsIndexRouteImport } from './routes/_protected/agents/index'
import { Route as ProtectedAgentsAgentIdRouteImport } from './routes/_protected/agents/$agentId'
import { Route as ProtectedJourneysIndexRouteImport } from './routes/_protected/journeys/index'
import { Route as ProtectedJourneysJourneyIdRouteImport } from './routes/_protected/journeys/$journeyId'
import { Route as ProtectedJourneysNewRouteImport } from './routes/_protected/journeys/new'
import { Route as ProtectedJourneysJourneyIdAssessmentsAssessmentIdRouteImport } from './routes/_protected/journeys/$journeyId_.assessments.$assessmentId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentsIndexRoute = ProtectedAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentsAgentIdRoute = ProtectedAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJourneysIndexRoute = ProtectedJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJourneysJourneyIdRoute =
  ProtectedJourneysJourneyIdRouteImport.update({
    id: '/journeys/$journeyId',
    path: '/journeys/$journeyId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedJourneysNewRoute = ProtectedJourneysNewRouteImport.update({
  id: '/journeys/new',
  path: '/journeys/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute =
  ProtectedJourneysJourneyIdAssessmentsAssessmentIdRouteImport.update({
    id: '/journeys/$journeyId_/assessments/$assessmentId',
    path: '/journeys/$journeyId/assessments/$assessmentId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof ProtectedSettingsRoute
  '/agents/$agentId': typeof ProtectedAgentsAgentIdRoute
  '/journeys/$journeyId': typeof ProtectedJourneysJourneyIdRoute
  '/journeys/new': typeof ProtectedJourneysNewRoute
  '/agents/': typeof ProtectedAgentsIndexRoute
  '/journeys/': typeof ProtectedJourneysIndexRoute
  '/journeys/$journeyId/assessments/$assessmentId': typeof ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof ProtectedIndexRoute
  '/agents/$agentId': typeof ProtectedAgentsAgentIdRoute
  '/journeys/$journeyId': typeof ProtectedJourneysJourneyIdRoute
  '/journeys/new': typeof ProtectedJourneysNewRoute
  '/agents': typeof ProtectedAgentsIndexRoute
  '/journeys': typeof ProtectedJourneysIndexRoute
  '/journeys/$journeyId/assessments/$assessmentId': typeof ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/agents/$agentId': typeof ProtectedAgentsAgentIdRoute
  '/_protected/journeys/$journeyId': typeof ProtectedJourneysJourneyIdRoute
  '/_protected/journeys/new': typeof ProtectedJourneysNewRoute
  '/_protected/agents/': typeof ProtectedAgentsIndexRoute
  '/_protected/journeys/': typeof ProtectedJourneysIndexRoute
  '/_protected/journeys/$journeyId_/assessments/$assessmentId': typeof ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/agents/$agentId'
    | '/journeys/$journeyId'
    | '/journeys/new'
    | '/agents/'
    | '/journeys/'
    | '/journeys/$journeyId/assessments/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/agents/$agentId'
    | '/journeys/$journeyId'
    | '/journeys/new'
    | '/agents'
    | '/journeys'
    | '/journeys/$journeyId/assessments/$assessmentId'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/agents/$agentId'
    | '/_protected/journeys/$journeyId'
    | '/_protected/journeys/new'
    | '/_protected/agents/'
    | '/_protected/journeys/'
    | '/_protected/journeys/$journeyId_/assessments/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agents/': {
      id: '/_protected/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof ProtectedAgentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agents/$agentId': {
      id: '/_protected/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof ProtectedAgentsAgentIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/journeys/': {
      id: '/_protected/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof ProtectedJourneysIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/journeys/$journeyId': {
      id: '/_protected/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof ProtectedJourneysJourneyIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/journeys/new': {
      id: '/_protected/journeys/new'
      path: '/journeys/new'
      fullPath: '/journeys/new'
      preLoaderRoute: typeof ProtectedJourneysNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/journeys/$journeyId_/assessments/$assessmentId': {
      id: '/_protected/journeys/$journeyId_/assessments/$assessmentId'
      path: '/journeys/$journeyId/assessments/$assessmentId'
      fullPath: '/journeys/$journeyId/assessments/$assessmentId'
      preLoaderRoute: typeof ProtectedJourneysJourneyIdAssessmentsAssessmentIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedAgentsAgentIdRoute: typeof ProtectedAgentsAgentIdRoute
  ProtectedJourneysJourneyIdRoute: typeof ProtectedJourneysJourneyIdRoute
  ProtectedJourneysNewRoute: typeof ProtectedJourneysNewRoute
  ProtectedAgentsIndexRoute: typeof ProtectedAgentsIndexRoute
  ProtectedJourneysIndexRoute: typeof ProtectedJourneysIndexRoute
  ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute: typeof ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedAgentsAgentIdRoute: ProtectedAgentsAgentIdRoute,
  ProtectedJourneysJourneyIdRoute: ProtectedJourneysJourneyIdRoute,
  ProtectedJourneysNewRoute: ProtectedJourneysNewRoute,
  ProtectedAgentsIndexRoute: ProtectedAgentsIndexRoute,
  ProtectedJourneysIndexRoute: ProtectedJourneysIndexRoute,
  ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute:
    ProtectedJourneysJourneyIdAssessmentsAssessmentIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
